apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: starwars-api-deploy
spec:
  selector:
    matchLabels:
      app: starwars-api
  replicas: 4 # réplicas
  template:
    metadata:
      labels:
        app: starwars-api
    spec:
      containers:
      - name: starwars-api
        image: daniloalves19/star-wars-api:0.0.1
        ports:
        - containerPort: 9000